PW.UI/Pages/CreateTestimonial.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PW.ApplicationContracts.Interfaces;
using PW.ApplicationContracts.ViewModels;

namespace PW.UI.Pages
{
    public class CreateTestimonialModel : PageModel
    {
        public TestimonialViewModel TestimonialVM { get; set; }
        private readonly ITestimonialApplication _itestimonialapplication;
        
        public string ErrorMessage { get; set; }
        public string SuccessMessage { get; set; }

        public CreateTestimonialModel(ITestimonialApplication itestimonialapplication)
        {
            _itestimonialapplication = itestimonialapplication;
        }

        public void OnGet()
        {

        }
        
        public void OnPost(TestimonialViewModel testimonialvm)
            {
            if (!ModelState.IsValid)
            {
                ErrorMessage = "اطلاعات ثبت نگردید. لطفاً مجدداً تلاش نمائید.";
            }
            else
            {
                _itestimonialapplication.Create(testimonialvm);
                SuccessMessage = "اطلاعات با موفقیت ثبت گردید. با تشکر.";
                ModelState.Clear();
            }
        }
    }

}

PW.UI/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace PW.UI.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

PW.UI/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PW.ApplicationContracts.Interfaces;
using PW.ApplicationContracts.ViewModels;

namespace PW.UI.Pages
{
    public class IndexModel : PageModel
    {
        private readonly IMessageApplication _imessageapplication;

        public IndexModel(IMessageApplication imessageapplication)
        {
            _imessageapplication = imessageapplication;
        }

        //[BindProperty(SupportsGet = true)]
        public MessageViewModel Message { get; set; }
        public string ErrorMessage { get; set; }
        public string SuccessMessage { get; set; }
        public void OnGet()
        {

        }
        public void OnPost(MessageViewModel message)
        {
            if (!ModelState.IsValid)
            {
                ErrorMessage = "اطلاعات ثبت نگردید. لطفاً مجدداً تلاش نمائید.";
            }
            else 
            { 
            _imessageapplication.Create(message);
            SuccessMessage = "اطلاعات با موفقیت ثبت گردید. با تشکر.";
            ModelState.Clear();
            }
        }
    }
}

PW.UI/ViewComponents/ContactViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using PW.ApplicationContracts.Interfaces;

namespace Emamzadeh.ViewComponents
{
    public class ContactViewComponent : ViewComponent
    {
        private readonly IProfessorApplication _iprofessorapplication;

        public ContactViewComponent(IProfessorApplication iprofessorapplication)
        {
            _iprofessorapplication = iprofessorapplication;
        }

        public IViewComponentResult Invoke()
        {
            var selectedprofessor = _iprofessorapplication.GetBy(1);
            return View("_Contact", selectedprofessor);
        }
    }
}

PW.UI/ViewComponents/CourseViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using PW.ApplicationContracts.Interfaces;

namespace Emamzadeh.ViewComponents
{
    public class CourseViewComponent : ViewComponent
    {
        private readonly ICourseApplication _icourseapplication;

        public CourseViewComponent(ICourseApplication icourseapplication)
        {
            _icourseapplication = icourseapplication;
        }

        public IViewComponentResult Invoke()
        {
            var courselist = _icourseapplication.GetAll();
            return View("_Courses", courselist);
        }
    }
}

PW.UI/ViewComponents/FileViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using PW.ApplicationContracts.Interfaces;
using System.Linq;

namespace Emamzadeh.ViewComponents
{
    public class FileViewComponent : ViewComponent
    {
        private readonly IFileApplication _ifileapplication;

        public FileViewComponent(IFileApplication ifileapplication)
        {
            _ifileapplication = ifileapplication;
        }

        public IViewComponentResult Invoke(int Id)
        {
            var fileslist = _ifileapplication.GetAll().Where(x=>x.FileTypeId == Id);
            return View("_File",fileslist);
        }
    }
}

PW.UI/ViewComponents/MenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using PW.ApplicationContracts.Interfaces;

namespace Emamzadeh.ViewComponents
{
    public class MenuViewComponent : ViewComponent
    {
        private readonly IProfessorApplication _iprofessorapplication;

        public MenuViewComponent(IProfessorApplication iprofessorapplication)
        {
            _iprofessorapplication = iprofessorapplication;
        }

        public IViewComponentResult Invoke()
        {
            var selectedprofessor = _iprofessorapplication.GetBy(1);
            return View("_Menu", selectedprofessor);
        }
    }
}

PW.UI/ViewComponents/ResumeViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using PW.ApplicationContracts.Interfaces;
using System.Linq;

namespace Emamzadeh.ViewComponents
{
    public class ResumeViewComponent : ViewComponent
    {
        private readonly IResumeApplication _iresumeapplication;

        public ResumeViewComponent(IResumeApplication iresumeapplication)
        {
            _iresumeapplication = iresumeapplication;
        }

        public IViewComponentResult Invoke()
        {
            var resumelist = _iresumeapplication.GetAll().OrderByDescending(x=>x.Priority);
            return View("_Resume", resumelist);
        }
    }
}

PW.UI/ViewComponents/TestimonialsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using PW.ApplicationContracts.Interfaces;

namespace Emamzadeh.ViewComponents
{
    public class TestimonialsViewComponent : ViewComponent
    {
        private readonly ITestimonialApplication _itestimonialapplication;

        public TestimonialsViewComponent(ITestimonialApplication itestimonialapplication)
        {
            _itestimonialapplication = itestimonialapplication;
        }

        public IViewComponentResult Invoke()
        {
            var testimonialslist = _itestimonialapplication.GetAll();
            return View("_Testimonials", testimonialslist);
        }
    }
}

PW.UI/Areas/AdminPanel/Pages/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Welcome to Dr.Emamzadeh Website - به وب سایت شخصی دکتر سید ابوالقاسم امام زاده خوش آمدید</title>
    <meta name="description" content="وب سایت شخصی دکتر ابوالقاسم امام زاده ، استاد دانشگاه - دکتری ریاضیات کاربردی - محاسبات عددی معادلات دیفرانسیل  روش وتری" />
    <meta name="keywords" content="وب سایت شخصی دکتر امام زاده ، استاد دانشگاه - دکتری ریاضیات کاربردی - محاسبات عددی معادلات دیفرانسیل  روش وتری" />
    <meta name="author" content="Dr.Emamzadeh - دکتر ابوالقاسم امامزاده" />

    <!-- Vendor Css-->
    <link rel="stylesheet" href="~/assets/css/vendor.css" />
    <link rel="stylesheet" href="~/assets/css/LineIcons.min.css" />
    <link rel="stylesheet" type="text/css" href="~/~/assets/css/photoswipe.min.css" />
    <link rel="stylesheet" type="text/css" href="~/assets/css/default-skin.min.css" />

    <!-- Settings style Css -->
    <link href="~/assets/css/settings.css" rel="stylesheet">

    <!-- TiffanyTemplate style Css -->
    <link href="~/assets/css/theme-grey.css" rel="stylesheet">

    <!-- Custom style Css -->
    <link href="~/assets/css/custom.css" rel="stylesheet">
</head>

<body data-spy="scroll" data-target=".navbar-collapse">


    <!-- START: Preloader -->
    <div id="preloader" class="preloader">
        <div class="spinner">
            <div class="spinner-grow" role="status">
            </div>
            <span class="sr-only">شکیبایی کنید...</span>
        </div>
        <div class="preloader-screens">
            <div></div>
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>
    <!-- END: Preloader -->
    <!-- START: Aside -->
    @await Component.InvokeAsync("Menu")
    <!-- START: Aside -->

    <div class="page-wrapper section-dark">

        @RenderBody()

        <partial name="Footer" />
    </div>


    <!-- Root element of PhotoSwipe. Must have class pswp. -->
    <div class="pswp" tabindex="-1" role="dialog" aria-hidden="true">

        <!-- Background of PhotoSwipe.
             It's a separate element, as animating opacity is faster than rgba(). -->
        <div class="pswp__bg"></div>

        <!-- Slides wrapper with overflow:hidden. -->
        <div class="pswp__scroll-wrap">

            <!-- Container that holds slides. PhotoSwipe keeps only 3 slides in DOM to save memory. -->
            <!-- don't modify these 3 pswp__item elements, data is added later on. -->
            <div class="pswp__container">
                <div class="pswp__item"></div>
                <div class="pswp__item"></div>
                <div class="pswp__item"></div>
            </div>

            <!-- Default (PhotoSwipeUI_Default) interface on top of sliding area. Can be changed. -->
            <div class="pswp__ui pswp__ui--hidden">
                <div class="pswp__top-bar">
                    <!--  Controls are self-explanatory. Order can be changed. -->
                    <div class="pswp__counter"></div>
                    <button class="pswp__button pswp__button--close" title="Close (Esc)"></button>
                    <button class="pswp__button pswp__button--share" title="Share"></button>
                    <button class="pswp__button pswp__button--fs" title="Toggle fullscreen"></button>
                    <button class="pswp__button pswp__button--zoom" title="Zoom in/out"></button>

                    <!-- Preloader demo https://codepen.io/dimsemenov/pen/yyBWoR -->
                    <!-- element will get class pswp__preloader--active when preloader is running -->
                    <div class="pswp__preloader">
                        <div class="pswp__preloader__icn">
                            <div class="pswp__preloader__cut">
                                <div class="pswp__preloader__donut"></div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="pswp__share-modal pswp__share-modal--hidden pswp__single-tap">
                    <div class="pswp__share-tooltip"></div>
                </div>

                <button class="pswp__button pswp__button--arrow--left" title="Previous (arrow left)">
                </button>

                <button class="pswp__button pswp__button--arrow--right" title="Next (arrow right)">
                </button>

                <div class="pswp__caption">
                    <div class="pswp__caption__center"></div>
                </div>
            </div>
        </div>
    </div>

    <!-- JAVASCRIPTS -->

    <script src="~/assets/js/vendor.js"></script>

    <script src="~/assets/js/parallax.min.js"></script>
    <script src="~/assets/js/photoswipe.min.js"></script>
    <script src="~/assets/js/photoswipe-ui-default.min.js"></script>


    <!-- Custom Js -->
    <script src="~/assets/js/imagesloaded.pkgd.js"></script>
    <script src="~/assets/js/jquery.shuffle.min.js"></script>
    <script src="~/assets/js/custom-shuffle-init.js"></script>
    <script src="~/assets/js/pswp.js"></script>
    <script src="~/assets/js/textition.min.js"></script>

    <script src="~/assets/js/custom.js"></script>

    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
</body>

</html>

PW.UI/Pages/CreateTestimonial.cshtml
@page
@model PW.UI.Pages.CreateTestimonialModel
<section>
    <div class="container">
        <div class="row"></div>

        <div class="row"></div>

        <div class="row"></div>

        <div class="row"></div>

        <div class="section-head">
            <span>دفترچه خاطرات</span>
            <h2>ارسال خاطرات</h2>
        </div>

        <div class="section-inner">
            <div class="contact-Otherdetails ">
                <div class="contact-form mt-5">
                    <form method="post">
                        <div asp-validation-summary="ModelOnly"></div>
                        <h5 class="section-subHead mb-2">فرم ارسال خاطرات</h5>
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="form-group mt-3 ">
                                    <input asp-for="TestimonialVM.StudentName" type="text" class="form-control b-box" placeholder="*نام شما">
                                    <span asp-validation-for="TestimonialVM.StudentName" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group mt-3 ">
                                    <input asp-for="@Model.TestimonialVM.StudentEmail" type="email" class="form-control b-box" placeholder="*ایمیل">
                                    <span asp-validation-for="@Model.TestimonialVM.StudentEmail" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="form-group mt-3 ">
                                    <input asp-for="@Model.TestimonialVM.UniversityName" type="text" class="form-control b-box" placeholder="*دانشگاه محل تحصیل">
                                    <span asp-validation-for="@Model.TestimonialVM.UniversityName" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group mt-3 ">
                                    <input asp-for="@Model.TestimonialVM.CourseName" type="text" class="form-control b-box" placeholder="*نام درس">
                                    <span asp-validation-for="@Model.TestimonialVM.CourseName" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="form-group mt-3 ">
                                    <input asp-for="@Model.TestimonialVM.EduYear" type="text" class="form-control b-box" placeholder="*سال تحصیلی">
                                    <span asp-validation-for="@Model.TestimonialVM.EduYear" class="text-danger"></span>

                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group mt-3 form-inline ">
                                    <label asp-for="@Model.TestimonialVM.StudentImg">تصویر شما</label>
                                    <input asp-for="@Model.TestimonialVM.StudentImg" type="file" class="form-control b-box">
                                    <span asp-validation-for="@Model.TestimonialVM.StudentImg" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="form-group mt-3 ">
                                    <input asp-for="@Model.TestimonialVM.Title" type="text" class="form-control b-box" placeholder="*عنوان خاطره">
                                    <span asp-validation-for="@Model.TestimonialVM.Title" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="form-group mt-3 ">
                                    <textarea asp-for="@Model.TestimonialVM.Description" rows="4" class="form-control b-box" placeholder="...متن خاطره"></textarea>
                                    <span asp-validation-for="@Model.TestimonialVM.Description" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-lg-12 text-center mt-4">
                                <button type="submit" class="btn">ارسال</button>
                            </div>
                        </div>
                        @*</div>*@
                    </form>
                </div>
            </div>
        </div>
        @if (!string.IsNullOrWhiteSpace(Model.SuccessMessage))
        {
            <div class="alert-success p-1 rounded-pill">
                <i class="alert-success"></i>
                <p>@Model.SuccessMessage</p>
            </div>
        }
        @if (!string.IsNullOrWhiteSpace(Model.ErrorMessage))
        {
            <div class="alert-danger p-1rounded-pill">
                <i class="alert-danger"></i>
                <p>@Model.ErrorMessage</p>
            </div>
        }
    </div>
</section>

PW.UI/Pages/Index.cshtml
@page
@model IndexModel
<!-- START: HOME -->
<section class="section section-home section-home-2 " id="home">

    <div id="scene">
        <img data-depth="0.1" class="shape1" src="~/assets/images/decor1.png" alt="Scene Images1">
        <img data-depth="0.1" class="shape4" src="~/assets/images/decor4.png" alt="Scene Images1">
        <img data-depth="0.1" class="shape5" src="~/assets/images/shape5.svg" alt="Scene Images1">
        <img data-depth="0.1" class="shape6" src="~/assets/images/shape6.svg" alt="Scene Images1">
        <img data-depth="0.2" class="shape2" src="~/assets/images/decor2.png" alt="Scene Images2">
        <img data-depth="0.4" class="shape3" src="~/assets/images/decor3.png" alt="Scene Images3">
        <img data-depth="0.2" class="shape7" src="~/assets/images/shape7.svg" alt="Scene Images3">
        <img data-depth="0.1" class="shape8" src="~/assets/images/shape8.svg" alt="Scene Images3">
    </div>

    <div class="container vh-100">
        <div class="row justify-content-center align-items-center section-home-in h-100vh">
            <img class="hero-img img-fluid rounded-full" src="~/assets/images/logoT.png" alt="Numerical Methods">
            <h1 class="my-4">
                @*<span id="autoplay">
                        <span>وب سایت شخصی</span>
                        <span>دکتر سید ابوالقاسم امام زاده</span>
                    </span>*@
            </h1>
        </div>
    </div>
    <div id="scroll-down"></div>
</section>
<!-- END: HOME -->
<!-- START: ABOUT -->
<partial name="About" />
<!-- END: ABOUT -->
<!-- START: Courses -->
@await Component.InvokeAsync("Course")
<!-- END: Courses -->
<!-- START: TESTIMONY -->
@await Component.InvokeAsync("Testimonials")
<!-- END: TESTIMONY -->
<!-- START: RESUME -->
@await Component.InvokeAsync("Resume")
<!-- END: RESUME -->
<!-- START: BLOG -->
<partial name="Blog" />
<!-- END: BLOG -->
<!-- START: CONTACT -->
@await Component.InvokeAsync("Contact")
@*@await Component.InvokeAsync("ContactSend", new { message = ViewBag.nt })*@
<section class="section section-contact" id="contact2">
    <div class="container">


        <div class="section-inner">
            <div class="contact-Otherdetails ">


                <div class="contact-form mt-5">
                    <form method="post">
                        <h5 class="section-subHead mb-2">فرم تماس</h5>
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="form-group mt-3 ">
                                    <input asp-for="Message.Name" type="text" class="form-control b-box" placeholder="*نام شما">
                                    <span asp-validation-for="Message.Name" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group mt-3 ">
                                    <input asp-for="Message.Email" type="email" class="form-control b-box" placeholder="*ایمیل">
                                    <span asp-validation-for="Message.Email" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="form-group mt-3 ">
                                    <input type="text" class="form-control b-box" asp-for="Message.Title" placeholder="موضوع...">
                                    <span asp-validation-for="Message.Title" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="form-group mt-3 ">
                                    <textarea asp-for="Message.Description" rows="4" class="form-control b-box" placeholder="پیام..."></textarea>
                                    <span asp-validation-for="Message.Description" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-lg-12 text-center mt-4">
                                <button type="submit" class="btn">ارسال</button>
                            </div>
                        </div>
                    </form>
                    @if (!string.IsNullOrWhiteSpace(Model.SuccessMessage))
                        {
                            <div class="alert-success p-1 rounded-pill">
                                <i class="alert-success"></i>
                                <p>@Model.SuccessMessage</p>
                            </div>
                        }
                        @if (!string.IsNullOrWhiteSpace(Model.ErrorMessage))
                        {
                            <div class="alert-danger p-1rounded-pill">
                                <i class="alert-danger"></i>
                                <p>@Model.ErrorMessage</p>
                            </div>
                        }
                </div>
            </div>
        </div>
    </div>
</section>
<!-- END: CONTACT -->

PW.UI/Pages/Shared/About.cshtml
<section class="section section-about " id="home">
    <div class="container">
        <div class="row justify-content-center align-items-center">
            <div class="col-md-7">
                <div class="hero-right mt-5 mt-md-0 text-center" data-wow-delay="300ms">
                    <h5>سلام !</h5>
                    <h2 class="my-4">
                        <span>وب سایت شخصی</span>
                        <span>دکتر سید ابوالقاسم امام زاده</span>
                    </h2>
                    <p>این سایت جهت اطلاع رسانی و همرسانی مطالب علمی و دوره های آموزشی و همچنین به اشتراک گذاری اطلاعات مربوطه طراحی و ایجاد گردیده است. در صورتی که هرگونه پیشنهاد و یا انتقاد نسبت به سایت دارید، در بخش «تماس با من»، مطلب مربوطه را به اشتراک گذارید.</p>
                    <div class="hero-right--btns my-4">
                        @*<a target="_blank" href="https://linkedin.com/" class="btn btn-link">بیشتر بدانید</a>*@
                        <a href="#resume" class="btn ripple">بیشتر...</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

PW.UI/Pages/Shared/_Layout.cshtml
@*@model Emamzadeh.Models.Professor*@
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Welcome to Dr.Emamzadeh Website - به وب سایت شخصی دکتر سید ابوالقاسم امام زاده خوش آمدید</title>
    <meta name="description" content="وب سایت شخصی دکتر ابوالقاسم امام زاده ، استاد دانشگاه - دکتری ریاضیات کاربردی - محاسبات عددی معادلات دیفرانسیل  روش وتری" />
    <meta name="keywords" content="وب سایت شخصی دکتر امام زاده ، استاد دانشگاه - دکتری ریاضیات کاربردی - محاسبات عددی معادلات دیفرانسیل  روش وتری" />
    <meta name="author" content="Dr.Emamzadeh - دکتر ابوالقاسم امامزاده" />

    <!-- Vendor Css-->
    <link rel="stylesheet" href="~/assets/css/vendor.css" />
    <link rel="stylesheet" href="~/assets/css/LineIcons.min.css" />
    <link rel="stylesheet" type="text/css" href="~/~/assets/css/photoswipe.min.css" />
    <link rel="stylesheet" type="text/css" href="~/assets/css/default-skin.min.css" />

    <!-- Settings style Css -->
    <link href="~/assets/css/settings.css" rel="stylesheet">

    <!-- TiffanyTemplate style Css -->
    <link href="~/assets/css/theme-grey.css" rel="stylesheet">

    <!-- Custom style Css -->
    <link href="~/assets/css/custom.css" rel="stylesheet">
</head>

<body data-spy="scroll" data-target=".navbar-collapse">


    <!-- START: Preloader -->
    <div id="preloader" class="preloader">
        <div class="spinner">
            <div class="spinner-grow" role="status">
            </div>
            <span class="sr-only">شکیبایی کنید...</span>
        </div>
        <div class="preloader-screens">
            <div></div>
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>
    <!-- END: Preloader -->
    <!-- START: Aside -->
    @await Component.InvokeAsync("Menu")
    <!-- START: Aside -->

    <div class="page-wrapper section-dark">

        @RenderBody()

        <partial name="Footer" />
    </div>


    <!-- Root element of PhotoSwipe. Must have class pswp. -->
    <div class="pswp" tabindex="-1" role="dialog" aria-hidden="true">

        <!-- Background of PhotoSwipe.
             It's a separate element, as animating opacity is faster than rgba(). -->
        <div class="pswp__bg"></div>

        <!-- Slides wrapper with overflow:hidden. -->
        <div class="pswp__scroll-wrap">

            <!-- Container that holds slides. PhotoSwipe keeps only 3 slides in DOM to save memory. -->
            <!-- don't modify these 3 pswp__item elements, data is added later on. -->
            <div class="pswp__container">
                <div class="pswp__item"></div>
                <div class="pswp__item"></div>
                <div class="pswp__item"></div>
            </div>

            <!-- Default (PhotoSwipeUI_Default) interface on top of sliding area. Can be changed. -->
            <div class="pswp__ui pswp__ui--hidden">
                <div class="pswp__top-bar">
                    <!--  Controls are self-explanatory. Order can be changed. -->
                    <div class="pswp__counter"></div>
                    <button class="pswp__button pswp__button--close" title="Close (Esc)"></button>
                    <button class="pswp__button pswp__button--share" title="Share"></button>
                    <button class="pswp__button pswp__button--fs" title="Toggle fullscreen"></button>
                    <button class="pswp__button pswp__button--zoom" title="Zoom in/out"></button>

                    <!-- Preloader demo https://codepen.io/dimsemenov/pen/yyBWoR -->
                    <!-- element will get class pswp__preloader--active when preloader is running -->
                    <div class="pswp__preloader">
                        <div class="pswp__preloader__icn">
                            <div class="pswp__preloader__cut">
                                <div class="pswp__preloader__donut"></div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="pswp__share-modal pswp__share-modal--hidden pswp__single-tap">
                    <div class="pswp__share-tooltip"></div>
                </div>

                <button class="pswp__button pswp__button--arrow--left" title="Previous (arrow left)">
                </button>

                <button class="pswp__button pswp__button--arrow--right" title="Next (arrow right)">
                </button>

                <div class="pswp__caption">
                    <div class="pswp__caption__center"></div>
                </div>
            </div>
        </div>
    </div>

    <!-- JAVASCRIPTS -->

    <script src="~/assets/js/vendor.js"></script>

    <script src="~/assets/js/parallax.min.js"></script>
    <script src="~/assets/js/photoswipe.min.js"></script>
    <script src="~/assets/js/photoswipe-ui-default.min.js"></script>


    <!-- Custom Js -->
    <script src="~/assets/js/imagesloaded.pkgd.js"></script>
    <script src="~/assets/js/jquery.shuffle.min.js"></script>
    <script src="~/assets/js/custom-shuffle-init.js"></script>
    <script src="~/assets/js/pswp.js"></script>
    <script src="~/assets/js/textition.min.js"></script>

    <script src="~/assets/js/custom.js"></script>

    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
</body>

</html>